language: python
python:
  - "2.7"
notifications:
    email:
      - coursys-help@sfu.ca
cache: pip
sudo: required
services:
  - docker
install:
  - docker pull ggbaker/coursys-test
script: "docker run ggbaker/django-coursys"