language: python
python:
  - "2.7"
notifications:
    email:
      - coursys-help@sfu.ca
cache: pip
before_install:
  - wget -P /tmp -nc http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/sqlite3_3.14.1-1build1_amd64.deb
  - wget -P /tmp -nc http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/libsqlite3-0_3.14.1-1build1_amd64.deb
  - wget -P /tmp -nc http://mirrors.kernel.org/ubuntu/pool/main/r/readline/libreadline7_7.0-0ubuntu2_amd64.deb
  - wget -P /tmp -nc http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_6.0+20160625-1ubuntu1_amd64.deb
  - wget -P /tmp -nc http://mirrors.kernel.org/ubuntu/pool/main/g/glibc/libc6_2.24-3ubuntu1_amd64.deb
  - sudo dpkg -i /tmp/*.deb
install: "pip install -r build_deps/working_deps.txt"
script: "python manage.py test"
sudo: required
branches:
  except:
    - django17
